Us 142 resize able columns edit/delete
evanhagood/desktop-data-manager pull request #11
Opened 2024-10-21 20:42 UTC by tlweave2

Added confirmation to delete. made columns resize-able, instituted a reset column button.

2024-10-23 19:25 UTC, qknowles requested changes
Our current version passes the CI. Were you not working with a current version?

2024-10-24 17:14 UTC, qknowles requested changes
Tim is going to attempt to default the date/time column width. Great job!

2024-10-25 05:10 UTC, tlweave2 commented
changed to calculate width of columns from width of contents, changed slider color.

2024-10-25 15:37 UTC, qknowles approved these changes

2024-10-25 15:38 UTC, merged